# Site settings
title: Scratcher Meetup
description: "Scratchが好きな子どものための交流イベント"
url           : "https://scratcher-meetup.github.io" # site url
baseurl       : "/" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "/assets/images/OGP/scrather-meetup.OGP.png" # image uri like logo/cover image for site seo

google_analytics  : G-QT63BYLJV6
twitter_username  : ""
comments_enabled  : false # if enabled (set to true), please provide your disqus_username
disqus_shortname  : ""
postshare_enabled : false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "Scratcher Meetup"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
# navbar:
#   - slug : about
#     title: About
#   - slug : blog
#     title: Blog

exclude:
  - "gulp"
  - "node_modules"
  - "bower"
  - "bower_components"
  - "config.rb"
  - "src"
  - "Gemfile"
  - "Gemfile.lock"
  - ".rvmrc"
  - ".rbenv-version"
  - "package.json"
  - "gulpfile.js"
  - "README.md"
  - "Rakefile"
  - "changelog.md"
  - "script"
  - "vendor"
  - "thinkspace.gemspec"
